sseHost: http://datapro.senseauto.com
sseBasePath: /api/sse-service/noauth
ads:
  profile: ad_system_common
authHeader: {}
alert:
  path: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key={}
  key: 5014f73a-0df4-4fef-a3ed-a68931ffccd9
  templates: "生成评测报告<font color=\"warning\">{}</font>错误， 请相关同事注意。\n >job名称：{} \n >创建人：{} \n >发生时间:<font color=\"comment\">{}</font> \n >job id: {} \n >错误详情:<font color=\"comment\">{}</font> \n"